#!/usr/bin/env bash
cd /home/ggw/ggw/data_exports/
if [ $? -eq 0 ]; then
 for f in *.csv; do mv "$f" "`echo $f | tr "[:lower:]" "[:upper:]"`"; done
else
 echo "Data Dir Not Found!"
fi
#Start Import
cd /home/ggw/ggw/
#./import_begin.sh
./update_begin.sh
