#!/usr/bin/env bash
#scp -i/home/digerpaji/.ssh/id_rsa_ggw /home/digerpaji/.dosemu/drive_c/exports/*.csv digerpaji@192.168.1.144:/home/digerpaji/ggw/data_exports
cp /home/general-goods/.dosemu/drive_c/exports/*.csv /home/ggw/ggw/data_exports
